### ISSUE TITLE
How about case insensitive left tree sorting?

### ISSUE THREAD

**Issue by himurovich** [modxorg/DocsApp#103]
## Summary

I could not find fastField package on the first try, it turned out to be at the tail of the list. Now we essentially have two lists one by one - the first starts with a capital letter, the second with a small one. 

![2021-03-06 17 52 52](https://user-images.githubusercontent.com/2815640/110231721-80220800-7f2a-11eb-8c09-1fc8e4776783.png)

## Why?

It is very convenient to quickly find a package by the first letter of the name in the left tree,  case of the first letter does not matter as for me here.

**Comment by Mark-H** [comment]
@himurovich (or @Ibochkarev) Could you check if the sorting is now also correct in Russian? It's using mb_strtolower so I hope that works as it should but a sanity check would be appreciated. :)

**Comment by Ibochkarev** [comment]
@Mark-H Now it works as it should. Thank! 👍

**Comment by himurovich** [comment]
Thank you @Mark-H, it works as expected!
