### ISSUE TITLE
Make the docs more accessible using ARIA attributes

### ISSUE THREAD

**Issue by JoshuaLuckers** [modxorg/DocsApp#18]
It would be great if the MODX documentation is also accessible for people with disabilities. We can do this by [using ARIA attributes](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA).

**Comment by Mark-H** [comment]
ARIA isn't needed if you just make things semantic from the start ;)

Good idea to at the very least run through some a11y testing though and to see what may need to be addressed with ARIA or other solutions. When I did a very quick lighthouse audit earlier, it only mentioned some slightly low contrast I think.

**Comment by christianseel** [comment]
This has been incorporated into the new design from the beginning. **So I'd close this general issue** and would ask people to open a new one if they spot any specific issue.

In general semantic markup has been used and aria attibutes added where needed. Skiplinks have been added and color choices where mad with AA or even AAA requirements in mind.
