### ISSUE TITLE
Allow links to wrap

### ISSUE THREAD

**Issue by christianseel** [modxorg/DocsApp#28]
Links (especially to the modx api) can be extremely long. We need to allow them to wrap.

<img width="1518" alt="Image 2019-03-30 at 8 18 04 PM" src="https://user-images.githubusercontent.com/482184/55280690-4fda9380-5329-11e9-8801-7b20faef1431.png">

**Comment by Ibochkarev** [comment]
@Mark-H Actual?

**Comment by Mark-H** [comment]
Nope, you fixed this :)
