### ISSUE TITLE
Change the font size and line spacing for menu and text

### ISSUE THREAD

**Issue by Ibochkarev** [modxorg/DocsApp#37]
## Summary

Change the font size and line spacing to improve the presentation of information and increase the usable space.

**Before editing:**

`font-size: 14px;
line-height: 1rem;`

![Index | MODX Documentation 2019-04-11 09-38-13](https://user-images.githubusercontent.com/2138260/55929329-ea967480-5c3d-11e9-9133-5fac5d07efa5.png)

**After editing:**
`font-size: 12px;
line-height: 1.5;`

![Index | MODX Documentation 2019-04-11 09-40-38](https://user-images.githubusercontent.com/2138260/55929332-ee29fb80-5c3d-11e9-887d-2c07058f0040.png)

**Comment by Mark-H** [comment]
No, 12px is too small for main body text. To my knowledge 16px is the best practice for content.

**Comment by Ibochkarev** [comment]
@markh ok!
