### ISSUE TITLE
Css style for blockquote

### ISSUE THREAD

**Issue by Ibochkarev** [modxorg/DocsApp#39]
## Summary
There are no styles for blockquote
![Custom manager themes : Client proofing : Building sites | MODX Documentation 2019-04-12 17-31-55](https://user-images.githubusercontent.com/2138260/56034490-3aae2d80-5d49-11e9-979b-11d7318003ee.png)

## Step to reproduce

https://docs.modx.org/current/en/building-sites/client-proofing/custom-manager-themes

**Comment by christianseel** [comment]
had been removed with the last large refactoring and need to be re-added (into `_typography.scss`)
