### ISSUE TITLE
Responsive issues on the home page

### ISSUE THREAD

**Issue by vmirkovicmodx** [modxorg/DocsApp#43]
## Summary

Viewing the docs page on mobile has a few issues

## Step to reproduce

Open the website on any mobile or open it through the responsive view through inspect element.

![image](https://user-images.githubusercontent.com/34141439/56248096-42eacd80-60a7-11e9-88cb-afde404cec26.png)

## Issues found

- MODX Logo section kicks Search almost off screen and even if you manage to reach it it won't work ( you can reach it in landscape mode ). Might be nice to move search inside the hamburger menu
- MODX Docs headline prints over the menu. A possible fix on line 662 of http://docs.modx.org/template/src/scss/app.scss:
```
 .content__inner {
    margin: 5rem 1rem 0 1rem;
  }
```
- The link svg icon seems to go all over the place. Possible fix on line 112:
```  &.link__external {
    position: relative;
    padding-right: 1.25rem;

    &:after {
      content: url(../src/svg/externallink.svg);
      position: absolute;
      bottom: 0;
      width: 14px;
      height: 1em;
      line-height: 1em;
      margin-left: 5px;
    }
```

Thanks!

**Comment by christianseel** [comment]
There is currently a PR in progress thats refactoring the markup and styles: https://github.com/modxorg/DocsApp/pull/40

So I'd vote to close this issue as it applies to the "old"(current) version online and not the new one.

**Comment by Mark-H** [comment]
We can keep this open until #40 lands and we can check that it is indeed fixed :)
