### ISSUE TITLE
Secure iframes with sandbox attribute

### ISSUE THREAD

**Issue by christianseel** [modxorg/DocsApp#44]
## Summary

`sandbox` attribute for `<iframe>`

## Why?
https://blog.dareboost.com/en/2015/07/securing-iframe-sandbox-attribute/

### Example
> I used something like this recently to embed google maps and dont worry about cookies and stuff: `<iframe seamlesssandbox="allow-forms allow-popups allow-scripts allow-pointer-lock" allowfullscreen></iframe>`

(by Joshua Lückers)

**Comment by Ibochkarev** [comment]
@Mark-H Fixed in https://github.com/modxorg/Docs/commit/529e8b5f5696818739abb33f1589bf52cb1a0314

**Comment by Ibochkarev** [comment]
@Mark-H Perhaps this is no longer relevant
