### ISSUE TITLE
Add translation for IN THIS DOCUMENT

### ISSUE THREAD

**Issue by Ibochkarev** [modxorg/DocsApp#48]
Regardless of the chosen language (RU, EN, NL) the line IN THIS DOCUMENT remains in English.

You need to make the IN THIS DOCUMENT header changeable depending on the selected language.

**Example**:
NL: IN DIT DOCUMENT
RU: IN THIS DOCUMENT

![image](https://user-images.githubusercontent.com/2138260/56887162-a820c480-6a92-11e9-9c06-cda7361346fc.png)

**Comment by Mark-H** [comment]
Yeah we'll need some i18n. Couple options I can think of:

- `gettext` https://www.sitepoint.com/easy-multi-language-twig-apps-with-gettext/
- `symfony/translator` https://symfony.com/doc/current/translation.html
- simple array file (json/yaml) in the root of a translation (modxorg/Docs) or in a directory in the app (modxorg/DocsApp) with the translations and a very basic custom translator service.

As we probably have less than 20 things we need to translate this way, I'm leaning towards the third option as it's probably simpler than learning the other - way more powerful - options.

**Comment by Mark-H** [comment]
New `lang.json` in the root now contains the different translated strings.
