### ISSUE TITLE
Footer is not pressed to the bottom.

### ISSUE THREAD

**Issue by Ibochkarev** [modxorg/DocsApp#53]
## Summary

Footer is not pressed to the bottom.

## Step to reproduce

https://docs.modx.org/current/en/building-sites

![image](https://user-images.githubusercontent.com/2138260/57951698-a10c0a00-790c-11e9-9240-f221d0c5d660.png)

**Comment by JoshuaLuckers** [comment]
This can be solved with Flexbox: https://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer/
