### ISSUE TITLE
Make the search input autofocus on home

### ISSUE THREAD

**Issue by JoshuaLuckers** [modxorg/DocsApp#57]
## Summary

Consider making the search input autofocus on the homepage so we can use the search function immediately without additional interaction (tab/click)

## Why?

I visit the homepage mostly to search for something. I now have to press tab or click in the input field when I want to search trough the documentation.

**Comment by Mark-H** [comment]
f433d28d4b65d9c7cfd9bf98583d2d0cdc777857 / a72ab4771367b9fdbd8d8d8310bf1c01ebd9cbc8
