### ISSUE TITLE
Disable browser autocompleting in the search form

### ISSUE THREAD

**Issue by JoshuaLuckers** [modxorg/DocsApp#58]
## Summary

Disable the browsers autocomplete function in the search form.

## Why?

The browsers autocomplete suggestions overlap the live search results.

![Example autocomplete](https://user-images.githubusercontent.com/1268085/64006099-f4981180-cb11-11e9-9c69-2703c2ca9c37.png)

**Comment by Ibochkarev** [comment]
Decision https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion
