### ISSUE TITLE
Add opengraph schemas to header

### ISSUE THREAD

**Issue by Mark-H** [modxorg/DocsApp#63]
### Summary

Add opengraph meta data to the docs.

### Why is it needed?

So social media can show better previews. 

### Suggested solution(s)

Something like:

```
<meta property="og:type" content="website">
<meta property="og:site_name" content="{'site_name'|config}">
<meta property="og:title" content="{$_modx->resource.pagetitle}">
<meta property="og:description" content="{$_modx->resource.description}">
<meta property="og:url" content="{'site_url'|config}">
<meta property="og:locale" content="ru_RU">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{$_modx->resource.pagetitle}">
<meta name="twitter:description" content="{$_modx->resource.description}">
<meta name="twitter:url" content="{'site_url'|config}{$uri}">
<meta name="twitter:domain" content="statum-trade.ru">
<meta name="twitter:site" content="@">
<meta name="twitter:creator" content="@...">
```

(Provided by @Ibochkarev)

### Related issue(s)/PR(s)
N/a.

**Comment by DESIGNfromWITHIN** [comment]
This needs automatic MODX tags like this?

`<meta property="og:title" content="[[*longtitle:default=`[[*pagetitle]]`]] | [[++site_name]]"/>
    <meta name="description" content="[[*description:notempty=`[[*description]]`:default=`[[+content:ellipsis=`155`]]`]]"/>
    <meta name="keywords" content="[[*keywords]]" />
    <meta name="author" content="[[++site_author]]" />
    <meta property="og:url" content="[[~[[*id]]? &scheme=`full`]]"/>
    <meta property="og:description" content="[[*description:notempty=`[[*description]]`:default=`[[+content:ellipsis=`155`]]`]]"/>`

**Comment by Ibochkarev** [comment]
> This needs automatic MODX tags like this?

This has been given as an example. The documentation website does not use CMS MODX
