### ISSUE TITLE
Update assets build workflow

### ISSUE THREAD

**Issue by Mark-H** [modxorg/DocsApp#82]
The build workflow for styles (`npm run build:css`) can no longer be executed on newer Macs because of node compatibility stuff. 

This is not my expertise, but on other projects I've simply replaced `node-sass` with `sass` in the package.json, and changed the command to `sass --style=compressed src/scss:dist`. When I try to do this for the docsapp however, it seems to be falling over on some of the magic in `template/src/scss/_breakpoints.scss` which I'm not sure how to best rewrite. 

@christianseel Any chance you could pitch in here and get the sass build workflow updated? JS workflow still works.

**Comment by christianseel** [comment]
@Mark-H I did mostly the same in recent projects. In this case i could imagine that the load-path argument is missing. This what I usually have in my package.json today:

```
"sass": "sass css/:dist --load-path=./ --style=expanded --source-map",
"build:css": "npm run sass -- --style=compressed --embed-sources",
"postbuild:css": "postcss dist/*.css --use autoprefixer --replace --map"
```

Could you double check if that helps? Otherwise I’m happy to help (not sure if I find time tomorrow through). Regards!

**Comment by Mark-H** [comment]
Thanks for the quick response! :)

Doesn't seem to do the trick unfortunately: 

```
> build:css
> sass src/scss:dist --load-path=./ --style=expanded --source-map

Error: (small: 0, medium: 640px, large: 1024px, xlarge: 1200px, xxlarge: 1440px) isn't a valid CSS value.
   ╷
25 │ $-zf-breakpoints-keys: map-to-list($breakpoints, 'keys');
   │                                    ^^^^^^^^^^^^
   ╵
  src/scss/_breakpoints.scss 25:36  @import
  src/scss/app.scss 12:9            root stylesheet
npm ERR! code 65
npm ERR! path /Users/mhamstra/Sites/docs.modx.local/app/public/template
npm ERR! command failed
npm ERR! command sh -c sass src/scss:dist --load-path=./ --style=expanded --source-map
```

**Comment by christianseel** [comment]
Merge request send ✅
